### ISSUE TITLE
tesseract "leaks distance" very slowly

### ISSUE THREAD

**Issue by glocke01** [kauewerner/Axioma#2]
If you leave tesseract running for 10+ hours, the points gradually come together until the magnitude of oscillations goes to <1 V at about 48 hours. Probably not a major problem for anyone since you can just reopen the patch to get back to normal. I guess if someone used tesseract in an art installation, maybe?

cool module, anyhow.

**Comment by kauewerner** [comment]
Thanks a lot for reporting this issue. I tried to reproduce it with a simple patch on Windows (just Tesseract connected to an Oscilloscope), for almost 48h, but neither the output reduced nor the points came together. Could you let me know and share the patch where you observed this issue? And also in which OS you were running it.
