### ISSUE TITLE
Plans for v2 ?

### ISSUE THREAD

**Issue by davephillips** [kauewerner/Axioma#3]
Any plans to update your excellent modules to VCV Rack 2 ?

Best regards,

Dave Phillips

**Comment by kauewerner** [comment]
Hi Dave, I have been away from VCV for a while but I am planning to return soon by updating to VCV Rack 2 :)

**Comment by firolightfog** [comment]
It has arrived under the cover of night ...

<img width="397" alt="image" src="https://user-images.githubusercontent.com/34127628/149122376-6e47d6d0-0f90-4d3f-8114-b431aacb4d42.png">
